### ISSUE TITLE
Conecta mas nao lista as entidades

### ISSUE THREAD

**Issue by nilcemar** [Douglas09/GeradorDeClasses_SimpleORM_MySql#1]
usando maria db nao lista os dados... ha algo a fazer?

**Comment by Douglas09** [comment]
Opa, boa noite... muda nos fontes no componente que lista as entidades...
certamente o nome do banco de dados está errado nele.

qualquer coisa manda
um whats ai 51 99550 2636

Em qua, 21 de out de 2020 23:09, nilcemar <notifications@github.com>
escreveu:
